#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May  5 11:04:03 2020

@author: jinlingxing
"""

'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        if len(s) == 0: #"", "y"
            return t[0]
        s = "".join(sorted(s))
        t = "".join(sorted(t))
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        return t[i+1]